# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Customer:
            algorithm: bcrypt
            cost: 12

        AppBundle\Entity\Shopper:
            algorithm: bcrypt
            cost: 12

    providers:
        customers_app:
            entity:
                class: AppBundle\Entity\Customer
                property: email

        shoppers_app:
            entity:
                class: AppBundle\Entity\Shopper
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        customerslogin:
            pattern:  ^/customersapi/login
            provider: customers_app
            stateless: true
            anonymous: true
            json_login:
                check_path:               /customersapi/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        customerssapi:
            pattern:   ^/customersapi
            provider: customers_app
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        shopperslogin:
            pattern:  ^/shoppersapi/login
            provider: shoppers_app
            stateless: true
            anonymous: true
            json_login:
                check_path:               /shoppersapi/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        shoppersapi:
            pattern:   ^/shoppersapi
            provider: shoppers_app
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: ~

    access_control:
        - { path: ^/customersapi/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customersapi,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/shoppersapi/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/shoppersapi,       roles: IS_AUTHENTICATED_FULLY }